import 'workbench_models.dart';
import 'workbench_view_data.dart';

const mockWorkbenchData = WorkbenchViewData(
  projects: [
    ProjectItem(
      id: 'project-codex-home',
      name: 'Codex Control Plane',
      rootPath: '/Users/robertsale/.codex',
      defaultCwd: '/Users/robertsale/.codex',
      autoRouteReplies: false,
      routeApprovalRequests: true,
      preferredModelProvider: null,
      orchestratorDefaultModel: 'gpt-5',
      orchestratorDefaultReasoningEffort: 'high',
      workerDefaultModel: 'gpt-5.4-mini',
      workerDefaultReasoningEffort: 'high',
      qaDefaultModel: 'gpt-5.4-mini',
      qaDefaultReasoningEffort: 'medium',
      designerDefaultModel: 'gpt-5.4-mini',
      designerDefaultReasoningEffort: 'high',
      requirementsReviewerDefaultModel: 'gpt-5.5',
      requirementsReviewerDefaultReasoningEffort: 'high',
      orchestratorDeveloperInstructions: 'Enforce bridge correctness and role policy.',
      workerDeveloperInstructions: 'Implement the requested slice directly.',
      qaDeveloperInstructions: 'Validate behavior and surface regressions.',
      designerDeveloperInstructions: 'Remove AI slop and push interface quality up.',
      operatorDeveloperInstructions: 'Coordinate local tooling and configuration.',
      hiddenDeveloperInstructions: 'Operate quietly and only when explicitly routed.',
      permanentRequirementComposables: ['non-negotiables'],
      isSelected: true,
    ),
    ProjectItem(
      id: 'project-ezra',
      name: 'Ezra',
      rootPath: '/Users/robertsale/Code/ezra/ezra/.worktrees',
      defaultCwd: '/Users/robertsale/Code/ezra/ezra/.worktrees',
      autoRouteReplies: true,
      routeApprovalRequests: true,
      preferredModelProvider: null,
      orchestratorDefaultModel: 'gpt-5',
      orchestratorDefaultReasoningEffort: 'high',
      workerDefaultModel: 'gpt-5.4-mini',
      workerDefaultReasoningEffort: 'high',
      qaDefaultModel: 'gpt-5.4-mini',
      qaDefaultReasoningEffort: 'medium',
      designerDefaultModel: 'gpt-5.4-mini',
      designerDefaultReasoningEffort: 'high',
      requirementsReviewerDefaultModel: 'gpt-5.5',
      requirementsReviewerDefaultReasoningEffort: 'high',
      orchestratorDeveloperInstructions: 'Keep Ezra review lanes disciplined.',
      workerDeveloperInstructions: 'Execute bounded implementation tasks.',
      qaDeveloperInstructions: 'Prove the slice with sanctioned validation.',
      designerDeveloperInstructions: 'Keep Ezra interfaces deliberate and specific.',
      operatorDeveloperInstructions: 'Handle coordination and environment issues.',
      hiddenDeveloperInstructions: 'Remain available for narrow support work.',
      permanentRequirementComposables: ['no-legacy'],
      isSelected: false,
    ),
  ],
  selection: WorkspaceSelection(
    projectId: 'project-codex-home',
    projectRootPath: '/Users/robertsale/.codex',
    projectOrchestratorThreadId: 'config-operator',
    projectOrchestratorName: 'Config Operator',
    threadId: 'config-operator',
    threadRole: 'operator',
    projectName: 'Codex Control Plane',
    threadName: 'Config Operator',
    connectionLabel: 'Bridge Connected',
    sandboxMode: 'danger-full-access',
    networkAccess: true,
    approvalPolicy: 'never',
    model: 'gpt-5',
    reasoningEffort: 'high',
    isRunning: true,
  ),
  availableModels: [
    ModelItem(id: 'gpt-5', name: 'GPT-5', hidden: false),
    ModelItem(id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', hidden: false),
  ],
  threads: [
    ThreadItem(
      id: 'config-operator',
      title: 'Config Operator',
      role: 'orchestrator',
      projectName: 'Codex Control Plane',
      preview: 'Bridge stable. Flutter shell scaffold next.',
      isRunning: true,
      unreadCount: 0,
      requirementReview: null,
    ),
    ThreadItem(
      id: 'approval-smoke',
      title: 'Approval Smoke Worker',
      role: 'worker',
      projectName: 'Codex Control Plane',
      preview: 'Approval and archive flow recovered.',
      isRunning: false,
      unreadCount: 0,
      requirementReview: null,
    ),
    ThreadItem(
      id: 'ezra-wave-b',
      title: 'Ezra Wave B',
      role: 'operator',
      projectName: 'Ezra',
      preview: 'Harness clarity issue tracked.',
      isRunning: false,
      unreadCount: 0,
      requirementReview: RequirementReviewSummary(
        activeRequirementCount: 3,
        storedRequirementCount: 3,
        requirementSetActive: true,
        status: 'failed',
        reviewerThreadId: 'ezra-wave-b-requirements-review',
        parentThreadId: 'ezra-wave-b',
        requirementSetId: 'req-ezra-wave-b',
        latestClaimPacket: null,
        latestVerdictPacket: null,
        passedCount: 1,
        failedCount: 1,
        blockedCount: 1,
        waiverRequiredCount: 0,
        unknownCount: 0,
        updatedAt: 1789179960,
        requirements: [
          RequirementReviewRequirement(
            key: 'nativeGuiIsSourceOfTruth',
            statement: 'The implementation must mirror the native Robdex GUI.',
            severity: 'blocker',
            verificationMethod: 'screenshotReview',
          ),
          RequirementReviewRequirement(
            key: 'noInventedProtocolShapes',
            statement: 'Do not invent websocket or HTTP event shapes.',
            severity: 'blocker',
            verificationMethod: 'diffReview',
          ),
          RequirementReviewRequirement(
            key: 'buildAndTypecheckPass',
            statement: 'Build and typecheck must pass before completion.',
            severity: 'high',
            verificationMethod: 'commandOutput',
          ),
        ],
        verdicts: [
          RequirementVerdictSummary(
            key: 'nativeGuiIsSourceOfTruth',
            verdict: 'fail',
            reason: 'Command rows still diverge from the native compact representation.',
            evidenceAssessment: 'Screenshot evidence shows different spacing and hierarchy.',
            requiredCorrection: 'Match native command row density and collapsed treatment.',
          ),
          RequirementVerdictSummary(
            key: 'noInventedProtocolShapes',
            verdict: 'pass',
            reason: 'The client consumes the bridge contract directly.',
            evidenceAssessment: 'No mock event aliases found in the inspected slice.',
            requiredCorrection: '',
          ),
          RequirementVerdictSummary(
            key: 'buildAndTypecheckPass',
            verdict: 'acceptedBlocked',
            reason: 'The worker hit a real external SDK credential blocker.',
            evidenceAssessment: 'Build output includes upstream 401 from private artifact host.',
            requiredCorrection: 'Owner must provide the missing credential before validation.',
          ),
        ],
      ),
    ),
  ],
  threadGroups: [
    ThreadGroupItem(
      id: 'group-core',
      title: 'Core Runtime',
      threadIds: ['config-operator'],
      isCollapsed: false,
    ),
  ],
  chatEntries: [
    ChatEntry(
      id: '1',
      author: 'Operator',
      displayLabel: 'Operator',
      timestamp: null,
      body: 'Build the new Robdex frontend here with shared Rust crates.',
    ),
    ChatEntry(
      id: '2',
      author: 'Config Operator',
      displayLabel: 'Config Operator',
      timestamp: null,
      body: 'Resuming interrupted QA-driven reliability sweep from existing agents without re-auditing from scratch.\n[in_progress] Resume the three blocked workers with exact scope and proof constraints.\n[pending] Keep the three QA agents held on warm simulator state pending their paired fixes.\n[pending] Monitor for worker replies and approval requests and steer immediately per constraints.',
      planItems: [
        PlanChecklistItem(
          text: 'Resume the three blocked workers with exact scope and proof constraints.',
          completed: false,
          status: 'in_progress',
        ),
        PlanChecklistItem(
          text: 'Keep the three QA agents held on warm simulator state pending their paired fixes.',
          completed: false,
          status: 'pending',
        ),
        PlanChecklistItem(
          text: 'Monitor for worker replies and approval requests and steer immediately per constraints.',
          completed: false,
          status: 'pending',
        ),
      ],
      isStreaming: true,
    ),
    ChatEntry(
      id: '3',
      author: 'Tooling',
      displayLabel: 'Tooling',
      timestamp: null,
      body: 'cargo check -p codex-robdex-bridge',
      kind: 'commandExecution',
      status: 'completed',
      command: 'cargo check -p codex-robdex-bridge',
      output: 'Finished `dev` profile [unoptimized + debuginfo] target(s) in 8.1s',
      processId: 'cmd-bridge-check',
      isTool: true,
    ),
    ChatEntry(
      id: '4',
      author: 'Tooling',
      displayLabel: 'Tooling',
      timestamp: null,
      body: 'flutter analyze',
      kind: 'commandExecution',
      status: 'in_progress',
      command: 'flutter analyze',
      processId: 'cmd-flutter-analyze',
      isStreaming: true,
      isTool: true,
    ),
    ChatEntry(
      id: '5',
      author: 'Tooling',
      displayLabel: 'Tooling',
      timestamp: null,
      body: 'flutter test test/chat_timeline_test.dart',
      kind: 'commandExecution',
      status: 'failed',
      command: 'flutter test test/chat_timeline_test.dart',
      output: 'Expected compact command row; found expanded scrollable output.',
      processId: 'cmd-flutter-test',
      isTool: true,
    ),
    ChatEntry(
      id: '6',
      author: 'Tooling',
      displayLabel: 'Tooling',
      subtitle: 'view_image',
      timestamp: null,
      body: 'Rendered screenshot preview',
      kind: 'imageView',
      status: 'completed',
      command: 'view_image /tmp/robdex-design-lab-static.png',
      output: '/tmp/robdex-design-lab-static.png',
      isTool: true,
    ),
    ChatEntry(
      id: '7',
      author: 'Tooling',
      displayLabel: 'Tooling',
      subtitle: 'mcp__openaiDeveloperDocs.search_openai_docs',
      timestamp: null,
      body: '{"query":"structured outputs strict json schema"}',
      kind: 'mcpToolCall',
      status: 'completed',
      command: 'search_openai_docs query="structured outputs strict json schema"',
      output: '3 matching official documentation pages.',
      isTool: true,
    ),
    ChatEntry(
      id: '8',
      author: 'Tooling',
      displayLabel: 'Diff',
      timestamp: null,
      body: 'Updated design-system package exports.',
      kind: 'fileChange',
      status: 'completed',
      command: 'frontend/robdex_app/packages/robdex_design_system/lib/robdex_design_system.dart',
      output: '1 file changed, 1 insertion.',
      isTool: true,
    ),
    ChatEntry(
      id: '9',
      author: 'System',
      displayLabel: 'System',
      timestamp: null,
      body: 'Context compacted; continuing with design lab fixture coverage.',
      kind: 'requestCompaction',
      status: 'completed',
      isTool: true,
    ),
    ChatEntry(
      id: '10',
      author: 'System',
      displayLabel: 'System',
      timestamp: null,
      body: 'Approval requested for a command that should use sanctioned privileged execution.',
      kind: 'approvalRequest',
      status: 'pending',
      command: 'flutter test test/ui/accounting/accounting_overview_existing_screenshot_test.dart',
      isTool: true,
    ),
    ChatEntry(
      id: '11',
      author: 'Config Operator',
      displayLabel: 'Config Operator',
      timestamp: null,
      body: 'Implemented fixture coverage for the chat timeline variants. The remaining work is visual tuning against screenshots, not data-model wiring.',
    ),
  ],
  contextWindowRemainingPercent: 83,
  workspaceFiles: [
    WorkspaceFile(
      path: 'frontend/robdex_app/lib/src/app/robdex_app.dart',
      kind: 'dart',
      status: 'new',
    ),
    WorkspaceFile(
      path: 'backend/crates/robdex-protocol/src/lib.rs',
      kind: 'rust',
      status: 'new',
    ),
    WorkspaceFile(
      path: 'frontend/robdex_app/rinf/schema.rinf',
      kind: 'rinf',
      status: 'new',
    ),
  ],
  inspectorFacts: [
    InspectorFact(label: 'Model', value: 'GPT-5'),
    InspectorFact(label: 'Sandbox', value: 'danger-full-access'),
    InspectorFact(label: 'Network', value: 'enabled'),
    InspectorFact(label: 'Selected Thread', value: 'Config Operator'),
  ],
  liveProcesses: [],
  pendingApprovals: [],
  workerMetadata: null,
  requirementReview: null,
  statusHeadline: 'Rust-first Robdex shell',
  statusDetail: 'UI regions are now modular. Next step is swapping mock data for live bridge state from shared Rust core.',
  composerHint: 'Composer is intentionally passive for now. The next slice wires commands and session flow through Rust.',
);
