import 'agent_runtime_control_tower_models.dart';

const mockAgentRuntimeRoleAdminEmpty = AgentRuntimeRoleAdminData(
  title: 'Role Admin (0)',
  subtitle: 'DB-backed immutable role versions',
  emptyTitle: 'No roles projected',
  emptyText: 'Hydrate the runtime projection to inspect role definitions.',
  rows: [],
  versionRows: [],
  validationErrors: [],
  actionStates: [],
);

const mockAgentRuntimeRoleAdminSelected = AgentRuntimeRoleAdminData(
  title: 'Role Admin (1)',
  subtitle: 'DB-backed immutable role versions',
  emptyTitle: 'No roles projected',
  emptyText: 'Hydrate the runtime projection to inspect role definitions.',
  rows: [
    AgentRuntimeRoleRow(
      id: 'runtime-allow',
      title: 'Runtime Allow',
      subtitle: '1.0.0 · gpt-5.4-mini',
      status: 'active',
      tone: 'success',
      currentVersionId: 'role-version-1',
    ),
  ],
  selectedDetail: AgentRuntimeRoleDetail(
    id: 'runtime-allow',
    displayName: 'Runtime Allow',
    version: '1.0.0',
    model: 'gpt-5.4-mini',
    status: 'active',
    instructionText: 'You are the runtime allow role. Inspect commands with cmd.describe().',
    capabilities: ['tool.execute_code'],
    policy: [AgentRuntimeRolePolicyRow(action: 'tool.execute_code', decision: 'allow')],
    routing: [AgentRuntimeFact(label: 'defaultRecipient', value: 'owner')],
    visibility: [AgentRuntimeFact(label: 'listed', value: 'true')],
    lifecycleAuthority: [AgentRuntimeFact(label: 'canArchiveAgents', value: 'false')],
  ),
  versionRows: [
    AgentRuntimeRoleVersionRow(versionId: 'role-version-1', version: '1.0.0', status: 'current', createdAt: '2026-06-01T12:00:00Z'),
    AgentRuntimeRoleVersionRow(versionId: 'role-version-0', version: '0.9.0', status: 'historical', createdAt: '2026-05-20T09:30:00Z'),
  ],
  editorDraft: AgentRuntimeRoleEditorDraft(
    roleId: 'runtime-allow',
    version: '1.0.0',
    displayName: 'Runtime Allow',
    model: 'gpt-5.4-mini',
    reasoningEffort: 'medium',
    instructionText: 'You are the runtime allow role. Inspect commands with cmd.describe().',
    capabilities: ['tool.execute_code'],
    policy: [AgentRuntimeRolePolicyRow(action: 'tool.execute_code', decision: 'allow')],
    routingMode: 'direct',
    routingReservedActions: ['message.send'],
    defaultRecipient: 'owner',
    allowedRecipients: ['owner'],
    listed: true,
    ownerVisible: true,
    canSpawnAgents: false,
    canArchiveAgents: false,
    lifecycleReservedActions: ['agent.archive'],
  ),
  validationErrors: [],
  actionStates: [
    AgentRuntimeActionItem(
      id: 'role:runtime-allow:validate',
      title: 'Validate draft',
      subtitle: 'Runs canonical role manifest, routing, and command-policy validation',
      kind: 'roleAdmin',
      stateText: 'Ready',
      tone: 'success',
    ),
    AgentRuntimeActionItem(
      id: 'role:runtime-allow:archive',
      title: 'Archive role',
      subtitle: 'Mutation waits for projection evidence',
      kind: 'roleAdmin',
      stateText: 'Can archive',
      tone: 'muted',
    ),
  ],
);

const mockAgentRuntimeRoleAdminInvalid = AgentRuntimeRoleAdminData(
  title: 'Role Admin (1)',
  subtitle: 'DB-backed immutable role versions',
  emptyTitle: 'No roles projected',
  emptyText: 'Hydrate the runtime projection to inspect role definitions.',
  rows: [
    AgentRuntimeRoleRow(id: 'draft-role', title: 'Draft Role', subtitle: '1.0.0 · gpt-5.4-mini', status: 'draft', tone: 'warning'),
  ],
  selectedDetail: null,
  versionRows: [],
  editorDraft: AgentRuntimeRoleEditorDraft(
    roleId: 'draft-role',
    version: '1.0.0',
    displayName: 'Draft Role',
    model: 'gpt-5.4-mini',
    reasoningEffort: 'medium',
    instructionText: 'Draft role instructions from the structured editor.',
    capabilities: ['tool.execute_code'],
    policy: [],
    routingMode: 'direct',
    routingReservedActions: ['message.send'],
    defaultRecipient: 'owner',
    allowedRecipients: ['owner'],
    listed: true,
    ownerVisible: true,
    canSpawnAgents: false,
    canArchiveAgents: false,
    lifecycleReservedActions: ['agent.archive'],
  ),
  validationErrors: ['capabilities must exactly match policy keys'],
  actionStates: [
    AgentRuntimeActionItem(
      id: 'role:draft-role:validate',
      title: 'Validate draft',
      subtitle: 'Runs canonical role manifest, routing, and command-policy validation',
      kind: 'roleAdmin',
      stateText: 'Fix validation errors',
      tone: 'danger',
    ),
  ],
);

const mockAgentRuntimeWorkflowMemoryEmpty = AgentRuntimeWorkflowMemoryData(
  title: 'Workflow Memory (0)',
  subtitle: 'execute_code/Starlark memories · inspector plus feedback',
  emptyTitle: 'No workflow memories',
  emptyText: 'No visible Starlark workflow memories are projected for the selected session.',
  rows: [],
  recentEvents: [],
  feedbackActions: [],
);

const mockAgentRuntimeWorkflowMemorySelected = AgentRuntimeWorkflowMemoryData(
  title: 'Workflow Memory (1)',
  subtitle: 'execute_code/Starlark memories · inspector plus feedback',
  emptyTitle: 'No workflow memories',
  emptyText: 'No visible Starlark workflow memories are projected for the selected session.',
  selectedMemoryId: 'memory-1',
  rows: [
    AgentRuntimeWorkflowMemoryRow(
      id: 'memory-1',
      title: 'Recover generated API drift',
      subtitle: 'project agent-runtime · Use generated packet ids before editing Dart bindings.',
      scopeType: 'project',
      projectKey: 'agent-runtime',
      helpfulScore: 0.42,
      promotedAt: '2026-06-16T10:15:00Z',
      sourceSessionId: 'session-1',
      tone: 'info',
      selected: true,
    ),
    AgentRuntimeWorkflowMemoryRow(
      id: 'memory-2',
      title: 'Use bounded output artifacts',
      subtitle: 'project agent-runtime · Retrieve logs by artifact handle.',
      scopeType: 'project',
      projectKey: 'agent-runtime',
      helpfulScore: 0.12,
      promotedAt: '2026-06-16T10:10:00Z',
      sourceSessionId: 'session-1',
      tone: 'info',
      selected: false,
    ),
  ],
  selectedDetail: AgentRuntimeWorkflowMemoryDetail(
    id: 'memory-1',
    title: 'Recover generated API drift',
    reason: 'Use generated packet ids before editing Dart bindings.',
    summary: 'When Rinf packets change, regenerate before adapting frontend code.',
    sourceSessionId: 'session-1',
    sourceScriptRunId: 'script-run-1',
    sourceStarlark: 'tips = workflow_memory.help()\\noutput(tips)',
    sourcePreview: 'tips = workflow_memory.help()\\noutput(tips)',
    provider: 'deterministic',
    model: 'workflow-memory-test',
    dimensions: 2560,
    storageType: 'halfvec',
    sourceHash: 'hash-abc',
    commandFingerprint: 'cmd.describe:v1',
    helpfulScore: 0.42,
    scopeLabel: 'project agent-runtime',
    feedbackSessionId: 'session-1',
    feedbackEnabled: true,
  ),
  recentEvents: [
    AgentRuntimeWorkflowMemoryEventRow(
      id: 'event-1',
      title: 'workflow_memory.promoted',
      subtitle: '{"sourceHash":"hash-abc"}',
      createdAt: '2026-06-16T10:15:00Z',
      tone: 'info',
    ),
    AgentRuntimeWorkflowMemoryEventRow(
      id: 'event-2',
      title: 'workflow_memory.helpful',
      subtitle: '{"source":"gui.controlTower"}',
      createdAt: '2026-06-16T10:25:00Z',
      tone: 'success',
    ),
  ],
  feedbackActions: [
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:attempted',
      title: 'Mark attempted',
      subtitle: 'Owner tried this workflow memory',
      kind: 'workflowMemoryFeedback',
      stateText: 'Session-scoped feedback',
      tone: 'warning',
    ),
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:helpful',
      title: 'Mark helpful',
      subtitle: 'Owner found this workflow memory useful',
      kind: 'workflowMemoryFeedback',
      stateText: 'Session-scoped feedback',
      tone: 'success',
    ),
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:notHelpful',
      title: 'Mark not helpful',
      subtitle: 'Owner found this workflow memory misleading',
      kind: 'workflowMemoryFeedback',
      stateText: 'Session-scoped feedback',
      tone: 'danger',
    ),
  ],
);

const mockAgentRuntimeIcloudRemoteMissing = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'missingProfile',
  tone: 'muted',
  title: 'No iCloud remote profile',
  message: 'iCloud sync supplies only a remote profile; refresh it on the server before connecting.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeIcloudRemoteMalformed = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'malformedProfile',
  tone: 'danger',
  title: 'iCloud profile is malformed',
  message: 'The synced remote profile is not valid Agent Runtime profile JSON.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeIcloudRemoteStale = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'staleProfile',
  tone: 'warning',
  title: 'iCloud remote profile is stale',
  message: 'The synced profile is older than the allowed freshness window; refresh it on the server before connecting.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeIcloudRemoteHealthy = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'remoteHealthy',
  tone: 'success',
  title: 'iCloud remote runtime reachable',
  message: 'iCloud supplied a remote profile and Rust verified /health; the target is connectable.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: true,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeIcloudRemoteUnreachable = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'remoteUnreachable',
  tone: 'danger',
  title: 'iCloud remote runtime unreachable',
  message: 'The profile exists, but Rust could not verify /health.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeImportedRemoteMissing = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'missingProfile',
  tone: 'muted',
  title: 'No imported remote profile',
  message: 'Import a remote profile JSON document; Rust stores an app-local copy and probes /health.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeImportedRemoteHealthy = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'remoteHealthy',
  tone: 'success',
  title: 'Imported remote runtime reachable',
  message: 'Rust validated the imported profile copy and verified /health; the target is connectable.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-16T10:20:00Z',
  connectable: true,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeImportedRemoteStale = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'staleProfile',
  tone: 'warning',
  title: 'Imported remote profile is stale',
  message: 'The imported profile is older than the allowed freshness window; import a fresh copy before connecting.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-15T08:00:00Z',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
);

const mockAgentRuntimeImportedRemoteMalformed = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'malformedProfile',
  tone: 'danger',
  title: 'Imported profile is malformed',
  message: 'Rust rejected the imported profile JSON before storing it as a connectable target.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeImportedRemoteUnreachable = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'remoteUnreachable',
  tone: 'danger',
  title: 'Imported remote runtime unreachable',
  message: 'The imported profile copy is valid, but Rust could not verify /health.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-16T10:20:00Z',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeDisconnected = AgentRuntimeControlTowerData(
  connectionState: 'disconnected',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'noDiscoveryFile',
    tone: 'muted',
    title: 'No local service discovery file',
    message: 'Start or refresh the local Agent Runtime service to create discovery.json.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteMissing,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteMissing,
  connectionTone: 'muted',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'No runtime connected',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'disconnected', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Connect to hydrate runtime sessions.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Select a session to inspect its event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No runtime action queue is loaded.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Transport', value: 'Rinf JSON packets'),
    AgentRuntimeFact(label: 'Source of truth', value: 'Rust/Postgres'),
  ],
  outputLog: ['No discovery packet loaded'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeConnecting = AgentRuntimeControlTowerData(
  connectionState: 'connecting',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteUnreachable,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteUnreachable,
  connectionTone: 'warning',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Connecting through Rust transport',
  watermarkLabel: 'pending',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'connecting', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Connection request', value: 'pending', tone: 'warning'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Waiting for the first Rust projection packet.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Timeline appears after session hydration.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'Action queue appears after runtime hydration.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Pending', value: 'connect-1'),
  ],
  outputLog: ['Sent GuiTransportRequestPacket.connect'],
  pendingRequestCount: 1,
);

const mockAgentRuntimeConnected = AgentRuntimeControlTowerData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
    runtimeIdentity: 'agent-runtime-local',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteHealthy,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteHealthy,
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime healthy',
  watermarkLabel: '42',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'streaming', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '2', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '2', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '1', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '1', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Timeline', value: '2', tone: 'info'),
  ],
  selectedSessionLabel: 'Runtime validation',
  sessionsTitle: 'Sessions (2)',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · Runtime validation',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (2)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions are visible in the current runtime projection.',
  timelineEmptyTitle: 'Runtime validation',
  timelineEmptyText: 'Select a session to hydrate its operations event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [
    AgentRuntimeSessionItem(
      id: 'session-a',
      title: 'Runtime validation',
      status: 'open',
      subtitle: 'runtime-allow · /Users/robertsale/.codex',
      groupLabel: 'Open',
      tone: 'success',
    ),
    AgentRuntimeSessionItem(
      id: 'session-b',
      title: 'Blocked command review',
      status: 'open',
      subtitle: '1 approval pending',
      groupLabel: 'Attention',
      tone: 'warning',
    ),
  ],
  timeline: [
    AgentRuntimeTimelineItem(
      id: 'event-41',
      title: 'tool.call execute_code',
      subtitle: 'Starlark completed',
      status: 'completed',
      tone: 'success',
    ),
    AgentRuntimeTimelineItem(
      id: 'event-42',
      title: 'approval.requested',
      subtitle: 'cmd.rg.audit requires owner approval',
      status: 'pending',
      tone: 'warning',
    ),
  ],
  actions: [
    AgentRuntimeActionItem(
      id: 'approval-1',
      title: 'Approve command execution',
      subtitle: 'canDecide=true · canResume=false',
      kind: 'approval',
      stateText: 'Needs decision',
      tone: 'warning',
    ),
    AgentRuntimeActionItem(
      id: 'registry-request-1',
      title: 'rg · audit',
      subtitle: 'add · project:alpha · ownerApproval',
      kind: 'commandRegistryRequest',
      stateText: 'Needs registry decision',
      tone: 'warning',
    ),
  ],
  roleAdmin: mockAgentRuntimeRoleAdminSelected,
  workflowMemory: mockAgentRuntimeWorkflowMemorySelected,
  controllerFacts: [
    AgentRuntimeFact(label: 'Selected session', value: 'session-a'),
    AgentRuntimeFact(label: 'Connection', value: 'streaming'),
  ],
  outputLog: ['projectionSnapshot watermark=42', 'controllerState streaming'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeError = AgentRuntimeControlTowerData(
  connectionState: 'failed',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'unhealthy',
    tone: 'danger',
    title: 'Local runtime is unhealthy',
    message: 'The service process exists but /health is failing.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
    baseUrl: 'http://127.0.0.1:8765',
    diagnostics: ['unhealthy: server process is alive but health check failed'],
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteMalformed,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteMalformed,
  connectionTone: 'danger',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime unavailable',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'failed', tone: 'danger'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Runtime sessions are unavailable until reconnect succeeds.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Timeline is unavailable while the runtime is disconnected.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No action queue is available while the runtime is unavailable.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminInvalid,
  workflowMemory: mockAgentRuntimeWorkflowMemorySelected,
  controllerFacts: [
    AgentRuntimeFact(label: 'Error code', value: 'unavailable'),
  ],
  outputLog: ['AgentRuntimeOutputSignal.error'],
  pendingRequestCount: 0,
  errorMessage: 'runtime server HTTP sync failed',
);

const mockAgentRuntimeEmpty = AgentRuntimeControlTowerData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteStale,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteStale,
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime connected · no sessions',
  watermarkLabel: '7',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'streaming', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions (0)',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions yet. Create one through a Rust operation when that UI is in scope.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Select a session to inspect its operations event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Connection', value: 'streaming'),
    AgentRuntimeFact(label: 'Action queue', value: 'empty'),
  ],
  outputLog: ['projectionSnapshot watermark=7'],
  pendingRequestCount: 0,
);
