import 'agent_runtime_control_tower_models.dart';

const mockAgentRuntimeDisconnected = AgentRuntimeControlTowerData(
  connectionState: 'disconnected',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'noDiscoveryFile',
    tone: 'muted',
    title: 'No local service discovery file',
    message: 'Start or refresh the local Agent Runtime service to create discovery.json.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
  ),
  connectionTone: 'muted',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'No runtime connected',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'disconnected', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Connect to hydrate runtime sessions.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Select a session to inspect its event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No runtime action queue is loaded.',
  sessions: [],
  timeline: [],
  actions: [],
  controllerFacts: [
    AgentRuntimeFact(label: 'Transport', value: 'Rinf JSON packets'),
    AgentRuntimeFact(label: 'Source of truth', value: 'Rust/Postgres'),
  ],
  outputLog: ['No discovery packet loaded'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeConnecting = AgentRuntimeControlTowerData(
  connectionState: 'connecting',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
  ),
  connectionTone: 'warning',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Connecting through Rust transport',
  watermarkLabel: 'pending',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'connecting', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Connection request', value: 'pending', tone: 'warning'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Waiting for the first Rust projection packet.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Timeline appears after session hydration.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'Action queue appears after runtime hydration.',
  sessions: [],
  timeline: [],
  actions: [],
  controllerFacts: [
    AgentRuntimeFact(label: 'Pending', value: 'connect-1'),
  ],
  outputLog: ['Sent GuiTransportRequestPacket.connect'],
  pendingRequestCount: 1,
);

const mockAgentRuntimeConnected = AgentRuntimeControlTowerData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
    runtimeIdentity: 'agent-runtime-local',
  ),
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime healthy',
  watermarkLabel: '42',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'streaming', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '2', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '2', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '1', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '1', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Timeline', value: '2', tone: 'info'),
  ],
  selectedSessionLabel: 'Runtime validation',
  sessionsTitle: 'Sessions (2)',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · Runtime validation',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (2)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions are visible in the current runtime projection.',
  timelineEmptyTitle: 'Runtime validation',
  timelineEmptyText: 'Select a session to hydrate its operations event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [
    AgentRuntimeSessionItem(
      id: 'session-a',
      title: 'Runtime validation',
      status: 'open',
      subtitle: 'runtime-allow · /Users/robertsale/.codex',
      groupLabel: 'Open',
      tone: 'success',
    ),
    AgentRuntimeSessionItem(
      id: 'session-b',
      title: 'Blocked command review',
      status: 'open',
      subtitle: '1 approval pending',
      groupLabel: 'Attention',
      tone: 'warning',
    ),
  ],
  timeline: [
    AgentRuntimeTimelineItem(
      id: 'event-41',
      title: 'tool.call execute_code',
      subtitle: 'Starlark completed',
      status: 'completed',
      tone: 'success',
    ),
    AgentRuntimeTimelineItem(
      id: 'event-42',
      title: 'approval.requested',
      subtitle: 'cmd.rg.audit requires owner approval',
      status: 'pending',
      tone: 'warning',
    ),
  ],
  actions: [
    AgentRuntimeActionItem(
      id: 'approval-1',
      title: 'Approve command execution',
      subtitle: 'canDecide=true · canResume=false',
      kind: 'approval',
      stateText: 'Needs decision',
      tone: 'warning',
    ),
    AgentRuntimeActionItem(
      id: 'registry-request-1',
      title: 'rg · audit',
      subtitle: 'add · project:alpha · ownerApproval',
      kind: 'commandRegistryRequest',
      stateText: 'Needs registry decision',
      tone: 'warning',
    ),
  ],
  controllerFacts: [
    AgentRuntimeFact(label: 'Selected session', value: 'session-a'),
    AgentRuntimeFact(label: 'Connection', value: 'streaming'),
  ],
  outputLog: ['projectionSnapshot watermark=42', 'controllerState streaming'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeError = AgentRuntimeControlTowerData(
  connectionState: 'failed',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'unhealthy',
    tone: 'danger',
    title: 'Local runtime is unhealthy',
    message: 'The service process exists but /health is failing.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
    baseUrl: 'http://127.0.0.1:8765',
    diagnostics: ['unhealthy: server process is alive but health check failed'],
  ),
  connectionTone: 'danger',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime unavailable',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'failed', tone: 'danger'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Runtime sessions are unavailable until reconnect succeeds.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Timeline is unavailable while the runtime is disconnected.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No action queue is available while the runtime is unavailable.',
  sessions: [],
  timeline: [],
  actions: [],
  controllerFacts: [
    AgentRuntimeFact(label: 'Error code', value: 'unavailable'),
  ],
  outputLog: ['AgentRuntimeOutputSignal.error'],
  pendingRequestCount: 0,
  errorMessage: 'runtime server HTTP sync failed',
);

const mockAgentRuntimeEmpty = AgentRuntimeControlTowerData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
  ),
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime connected · no sessions',
  watermarkLabel: '7',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'streaming', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'none selected',
  sessionsTitle: 'Sessions (0)',
  sessionsSubtitle: 'Grouped by Rust-owned operational state',
  timelineTitle: 'Selected session stream · none selected',
  timelineSubtitle: 'Operations event stream, not a chat transcript',
  actionsTitle: 'Action queue (0)',
  actionsSubtitle: 'Approvals, resumable work, and registry requests',
  detailTitle: 'Controller detail',
  detailSubtitle: 'Rust-owned controller facts',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions yet. Create one through a Rust operation when that UI is in scope.',
  timelineEmptyTitle: 'none selected',
  timelineEmptyText: 'Select a session to inspect its operations event stream.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [],
  timeline: [],
  actions: [],
  controllerFacts: [
    AgentRuntimeFact(label: 'Connection', value: 'streaming'),
    AgentRuntimeFact(label: 'Action queue', value: 'empty'),
  ],
  outputLog: ['projectionSnapshot watermark=7'],
  pendingRequestCount: 0,
);
