import 'agent_runtime_workbench_models.dart';
import 'conversation_shell_models.dart';
import 'workbench_models.dart';

const mockAgentRuntimeRoleEditorOptions = AgentRuntimeRoleEditorOptions(
  models: ['gpt-5.5', 'gpt-5.4-mini', 'codex-live-model'],
  reasoningEfforts: ['low', 'medium', 'high'],
  capabilities: ['tool.execute_code', 'tool.request_command_registry_change', 'fs.read', 'fs.write', 'patch.apply', 'workflow_memory.search', 'workflow_memory.feedback', 'command_registry.apply'],
  policyActions: ['tool.execute_code', 'tool.request_command_registry_change', 'fs.read', 'fs.write', 'patch.apply', 'workflow_memory.search', 'workflow_memory.feedback', 'command_registry.apply'],
  policyDecisions: ['allow', 'deny', 'ownerApproval'],
  routingModes: ['direct'],
  recipients: ['owner', 'runtime-safe-builder', 'orchestrator-reviewer'],
  reservedActions: ['message.send', 'agent.archive', 'command_registry.apply', 'workflow_memory.feedback'],
);

const mockAgentRuntimeRoleAdminEmpty = AgentRuntimeRoleAdminData(
  title: 'Role Admin (0)',
  subtitle: 'Edit roles and versions',
  emptyTitle: 'No roles loaded',
  emptyText: 'No role definitions are loaded for this runtime.',
  rows: [],
  versionRows: [],
  validationErrors: [],
  actionStates: [],
  editorOptions: mockAgentRuntimeRoleEditorOptions,
);

const mockAgentRuntimeRoleAdminSelected = AgentRuntimeRoleAdminData(
  title: 'Role Admin (6)',
  subtitle: 'Edit roles and versions',
  emptyTitle: 'No roles loaded',
  emptyText: 'No role definitions are loaded for this runtime.',
  rows: [
    AgentRuntimeRoleRow(
      id: 'runtime-allow',
      title: 'Runtime Allow',
      subtitle: '3.2.0 · gpt-5.5 · owner-visible · direct',
      status: 'active',
      tone: 'success',
      currentVersionId: 'role-version-1',
    ),
    AgentRuntimeRoleRow(id: 'runtime-safe-builder', title: 'Runtime Safe Builder', subtitle: '2.1.3 · gpt-5.5 · owner-visible · direct', status: 'active', tone: 'success', currentVersionId: 'role-version-safe'),
    AgentRuntimeRoleRow(id: 'orchestrator-reviewer', title: 'Orchestrator Reviewer', subtitle: '1.8.0 · gpt-5.5 · orchestrator-visible · direct', status: 'active', tone: 'success', currentVersionId: 'role-version-reviewer'),
    AgentRuntimeRoleRow(id: 'owner-approval-gate', title: 'Owner Approval Gate', subtitle: '1.4.2 · gpt-4o · approval-gated · owner-only', status: 'archived', tone: 'danger', currentVersionId: 'role-version-gate'),
    AgentRuntimeRoleRow(id: 'workflow-memory-agent', title: 'Workflow Memory Agent', subtitle: '0.3.0-draft · gpt-5.5 · hidden · owner-only', status: 'draft', tone: 'warning'),
    AgentRuntimeRoleRow(id: 'patch-only-worker', title: 'Patch Only Worker', subtitle: '1.6.1 · gpt-5.5 · owner-visible · direct', status: 'active', tone: 'success', currentVersionId: 'role-version-patch'),
  ],
  selectedDetail: AgentRuntimeRoleDetail(
    id: 'runtime-allow',
    displayName: 'Runtime Allow',
    version: '3.2.0',
    model: 'gpt-5.5',
    status: 'active',
    instructionText: '# Runtime Role Instructions\n\nYou are an execution-capable agent.\nUse native tools only when runtime work is required and policy allows.\nPreserve auditability, determinism, and the system’s safety boundaries.\nDefault to safe completion boundaries and minimize side effects.\n\nWhen uncertain, ask for clarity.\nDo not assume permissions not granted by policy.',
    capabilities: ['tool.execute_code', 'tool.request_command_registry_change', 'fs.read', 'fs.write', 'patch.apply', 'workflow_memory.search', 'workflow_memory.feedback', 'command_registry.apply'],
    policy: [
      AgentRuntimeRolePolicyRow(action: 'tool.execute_code', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'tool.request_command_registry_change', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'fs.read', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'fs.write', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'patch.apply', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'workflow_memory.search', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'workflow_memory.feedback', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'command_registry.apply', decision: 'ownerApproval'),
    ],
    routing: [AgentRuntimeFact(label: 'Default recipient', value: 'Owner')],
    visibility: [AgentRuntimeFact(label: 'Listed', value: 'Yes')],
    lifecycleAuthority: [AgentRuntimeFact(label: 'Archive authority', value: 'No')],
  ),
  versionRows: [
    AgentRuntimeRoleVersionRow(versionId: 'role-version-1', version: '3.2.0', status: 'current', createdAt: '2026-06-01T12:00:00Z'),
    AgentRuntimeRoleVersionRow(versionId: 'role-version-0', version: '3.1.0', status: 'historical', createdAt: '2026-05-20T09:30:00Z'),
    AgentRuntimeRoleVersionRow(versionId: 'role-version-archived', version: '2.4.1', status: 'archived', createdAt: '2026-04-18T09:11:02Z'),
  ],
  editorDraft: AgentRuntimeRoleEditorDraft(
    roleId: 'runtime-allow',
    version: '3.2.0',
    displayName: 'Runtime Allow',
    model: 'gpt-5.5',
    reasoningEffort: 'medium',
    instructionText: '# Runtime Role Instructions\n\nYou are an execution-capable agent.\nUse native tools only when runtime work is required and policy allows.\nPreserve auditability, determinism, and the system’s safety boundaries.\nDefault to safe completion boundaries and minimize side effects.\n\nWhen uncertain, ask for clarity.\nDo not assume permissions not granted by policy.',
    capabilities: ['tool.execute_code', 'tool.request_command_registry_change', 'fs.read', 'fs.write', 'patch.apply', 'workflow_memory.search', 'workflow_memory.feedback', 'command_registry.apply'],
    policy: [
      AgentRuntimeRolePolicyRow(action: 'tool.execute_code', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'tool.request_command_registry_change', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'fs.read', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'fs.write', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'patch.apply', decision: 'ownerApproval'),
      AgentRuntimeRolePolicyRow(action: 'workflow_memory.search', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'workflow_memory.feedback', decision: 'allow'),
      AgentRuntimeRolePolicyRow(action: 'command_registry.apply', decision: 'ownerApproval'),
    ],
    routingMode: 'direct',
    routingReservedActions: ['message.send', 'message.route'],
    defaultRecipient: 'owner',
    allowedRecipients: ['owner', 'orchestrator-reviewer', 'runtime-safe-builder'],
    listed: true,
    ownerVisible: true,
    canSpawnAgents: false,
    canArchiveAgents: false,
    lifecycleReservedActions: ['agent.spawn', 'agent.archive'],
  ),
  validationErrors: [],
  actionStates: [
    AgentRuntimeActionItem(
      id: 'role:runtime-allow:validate',
      title: 'Validate draft',
      subtitle: 'Checks the draft before saving',
      kind: 'roleAdmin',
      stateText: 'Ready',
      tone: 'success',
    ),
    AgentRuntimeActionItem(
      id: 'role:runtime-allow:archive',
      title: 'Archive role',
      subtitle: 'Updates after the runtime confirms the change',
      kind: 'roleAdmin',
      stateText: 'Can archive',
      tone: 'muted',
    ),
  ],
  editorOptions: mockAgentRuntimeRoleEditorOptions,
);

const mockAgentRuntimeRoleAdminInvalid = AgentRuntimeRoleAdminData(
  title: 'Role Admin (1)',
  subtitle: 'Edit roles and versions',
  emptyTitle: 'No roles loaded',
  emptyText: 'No role definitions are loaded for this runtime.',
  rows: [
    AgentRuntimeRoleRow(id: 'draft-role', title: 'Draft Role', subtitle: '1.0.0 · gpt-5.4-mini', status: 'draft', tone: 'warning'),
  ],
  selectedDetail: null,
  versionRows: [],
  editorDraft: AgentRuntimeRoleEditorDraft(
    roleId: 'draft-role',
    version: '1.0.0',
    displayName: 'Draft Role',
    model: 'gpt-5.4-mini',
    reasoningEffort: 'medium',
    instructionText: 'Draft role instructions from the structured editor.',
    capabilities: ['Execute code'],
    policy: [],
    routingMode: 'Direct',
    routingReservedActions: ['Send message'],
    defaultRecipient: 'Owner',
    allowedRecipients: ['Owner'],
    listed: true,
    ownerVisible: true,
    canSpawnAgents: false,
    canArchiveAgents: false,
    lifecycleReservedActions: ['Archive agent'],
  ),
  validationErrors: ['Capabilities and permission rules must match'],
  actionStates: [
    AgentRuntimeActionItem(
      id: 'role:draft-role:validate',
      title: 'Validate draft',
      subtitle: 'Checks the draft before saving',
      kind: 'roleAdmin',
      stateText: 'Fix validation errors',
      tone: 'danger',
    ),
  ],
  editorOptions: mockAgentRuntimeRoleEditorOptions,
);

const mockAgentRuntimeWorkflowMemoryEmpty = AgentRuntimeWorkflowMemoryData(
  title: 'Workflow Memory (0)',
  subtitle: 'Review saved workflows',
  emptyTitle: 'No workflow memories',
  emptyText: 'No saved workflows are visible for this session.',
  rows: [],
  recentEvents: [],
  feedbackActions: [],
);

const mockAgentRuntimeWorkflowMemorySelected = AgentRuntimeWorkflowMemoryData(
  title: 'Workflow Memory (1)',
  subtitle: 'Review saved workflows',
  emptyTitle: 'No workflow memories',
  emptyText: 'No saved workflows are visible for this session.',
  selectedMemoryId: 'memory-1',
  rows: [
    AgentRuntimeWorkflowMemoryRow(
      id: 'memory-1',
      title: 'Review interface changes',
      subtitle: 'Regenerate app interfaces before updating screens.',
      scopeType: 'project',
      projectKey: 'agent-runtime',
      helpfulScore: 0.42,
      promotedAt: '2026-06-16T10:15:00Z',
      sourceSessionId: 'session-1',
      tone: 'info',
      selected: true,
    ),
    AgentRuntimeWorkflowMemoryRow(
      id: 'memory-2',
      title: 'Use saved output excerpts',
      subtitle: 'Review large logs through saved excerpts.',
      scopeType: 'project',
      projectKey: 'agent-runtime',
      helpfulScore: 0.12,
      promotedAt: '2026-06-16T10:10:00Z',
      sourceSessionId: 'session-1',
      tone: 'info',
      selected: false,
    ),
  ],
  selectedDetail: AgentRuntimeWorkflowMemoryDetail(
    id: 'memory-1',
    title: 'Review interface changes',
    reason: 'Regenerate typed app interfaces before updating screens.',
    summary: 'When runtime messages change, regenerate app interfaces before updating screens.',
    sourceSessionId: 'session-1',
    sourceScriptRunId: 'script-run-1',
    sourceStarlark: 'tips = saved_workflow.help()\\noutput(tips)',
    sourcePreview: 'tips = saved_workflow.help()\\noutput(tips)',
    provider: 'Local',
    model: 'Memory index',
    dimensions: 2560,
    storageType: 'Vector store',
    sourceHash: 'Saved source',
    commandFingerprint: 'Command review',
    helpfulScore: 0.42,
    scopeLabel: 'project agent-runtime',
    feedbackSessionId: 'session-1',
    feedbackEnabled: true,
  ),
  recentEvents: [
    AgentRuntimeWorkflowMemoryEventRow(
      id: 'event-1',
      title: 'Saved for reuse',
      subtitle: 'Recorded after a successful workflow',
      createdAt: '2026-06-16T10:15:00Z',
      tone: 'info',
    ),
    AgentRuntimeWorkflowMemoryEventRow(
      id: 'event-2',
      title: 'Marked helpful',
      subtitle: 'Owner feedback recorded',
      createdAt: '2026-06-16T10:25:00Z',
      tone: 'success',
    ),
  ],
  feedbackActions: [
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:attempted',
      title: 'Mark attempted',
      subtitle: 'Mark this workflow as tried',
      kind: 'workflowMemoryFeedback',
      stateText: 'Ready',
      tone: 'warning',
    ),
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:helpful',
      title: 'Mark helpful',
      subtitle: 'Mark this workflow as useful',
      kind: 'workflowMemoryFeedback',
      stateText: 'Ready',
      tone: 'success',
    ),
    AgentRuntimeActionItem(
      id: 'workflow-memory:memory-1:notHelpful',
      title: 'Mark not helpful',
      subtitle: 'Owner found this workflow memory misleading',
      kind: 'workflowMemoryFeedback',
      stateText: 'Ready',
      tone: 'danger',
    ),
  ],
);

const mockAgentRuntimeIcloudRemoteMissing = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'missingProfile',
  tone: 'muted',
  title: 'No iCloud remote profile',
  message: 'iCloud sync supplies only a remote profile; refresh it on the server before connecting.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeIcloudRemoteMalformed = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'malformedProfile',
  tone: 'danger',
  title: 'iCloud profile is malformed',
  message: 'The synced remote profile is not valid Agent Runtime profile JSON.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeIcloudRemoteStale = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'staleProfile',
  tone: 'warning',
  title: 'iCloud remote profile is stale',
  message: 'The synced profile is older than the allowed freshness window; refresh it on the server before connecting.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeIcloudRemoteHealthy = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'remoteHealthy',
  tone: 'success',
  title: 'iCloud remote runtime reachable',
  message: 'iCloud supplied a remote profile and the health check passed.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: true,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeIcloudRemoteUnreachable = AgentRuntimeDiscoveryInfo(
  sourceType: 'iCloudRemoteProfile',
  sourcePath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  state: 'remoteUnreachable',
  tone: 'danger',
  title: 'iCloud remote runtime unreachable',
  message: 'The profile exists, but the health check failed.',
  discoveryPath: '~/Library/Mobile Documents/com~apple~CloudDocs/Robdex Agent Runtime/remote-profile.json',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeImportedRemoteMissing = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'missingProfile',
  tone: 'muted',
  title: 'No imported remote profile',
  message: 'Import a remote profile document. The app saves a copy and checks health before connecting.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeImportedRemoteHealthy = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'remoteHealthy',
  tone: 'success',
  title: 'Imported remote runtime reachable',
  message: 'The imported profile is valid and the health check passed.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-16T10:20:00Z',
  connectable: true,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeImportedRemoteStale = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'staleProfile',
  tone: 'warning',
  title: 'Imported remote profile is stale',
  message: 'The imported profile is older than the allowed freshness window; import a fresh copy before connecting.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-15T08:00:00Z',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
);

const mockAgentRuntimeImportedRemoteMalformed = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'malformedProfile',
  tone: 'danger',
  title: 'Imported profile is malformed',
  message: 'The imported profile is not valid and was not saved as a connection target.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  connectable: false,
);

const mockAgentRuntimeImportedRemoteUnreachable = AgentRuntimeDiscoveryInfo(
  sourceType: 'importedRemoteProfile',
  sourcePath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  state: 'remoteUnreachable',
  tone: 'danger',
  title: 'Imported remote runtime unreachable',
  message: 'The imported profile is valid, but the health check failed.',
  discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/imported-remote-profile/remote-profile.json',
  lastImportedAt: '2026-06-16T10:20:00Z',
  connectable: false,
  baseUrl: 'http://robertmsale._peer.internal:8765',
  healthUrl: 'http://robertmsale._peer.internal:8765/health',
);

const mockAgentRuntimeDisconnected = AgentRuntimeWorkbenchData(
  connectionState: 'disconnected',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'noDiscoveryFile',
    tone: 'muted',
    title: 'No local service discovery file',
    message: 'Start or refresh the local Agent Runtime service to create discovery.json.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteMissing,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteMissing,
  connectionTone: 'muted',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'No runtime connected',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'Not connected', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'No session selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Sessions needing attention',
  timelineTitle: 'Selected session · No session selected',
  timelineSubtitle: 'Recent activity',
  actionsTitle: 'Attention (0)',
  actionsSubtitle: 'Items waiting for owner action',
  detailTitle: 'Runtime detail',
  detailSubtitle: 'Runtime status',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Connect to hydrate runtime sessions.',
  timelineEmptyTitle: 'No session selected',
  timelineEmptyText: 'Select a session to inspect recent activity.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No action items need attention.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Connection', value: 'Waiting for setup'),
    AgentRuntimeFact(label: 'Storage', value: 'Ready after connection'),
  ],
  outputLog: ['No discovery result loaded'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeConnecting = AgentRuntimeWorkbenchData(
  connectionState: 'connecting',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteUnreachable,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteUnreachable,
  connectionTone: 'warning',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Connecting',
  watermarkLabel: 'pending',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'Connecting', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Connection request', value: 'In progress', tone: 'warning'),
  ],
  selectedSessionLabel: 'No session selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Sessions needing attention',
  timelineTitle: 'Selected session · No session selected',
  timelineSubtitle: 'Recent activity',
  actionsTitle: 'Attention (0)',
  actionsSubtitle: 'Items waiting for owner action',
  detailTitle: 'Runtime detail',
  detailSubtitle: 'Runtime status',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Waiting for the runtime to load sessions.',
  timelineEmptyTitle: 'No session selected',
  timelineEmptyText: 'Timeline appears after session hydration.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'Items needing attention appear here.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Connection request', value: 'In progress'),
  ],
  outputLog: ['Connection request sent'],
  pendingRequestCount: 1,
);

const mockAgentRuntimeConnected = AgentRuntimeWorkbenchData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
    healthUrl: 'http://127.0.0.1:8765/health',
    webSocketUrl: 'ws://127.0.0.1:8765/state/ws',
    runtimeIdentity: 'agent-runtime-local',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteHealthy,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteHealthy,
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime healthy',
  watermarkLabel: 'current',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'Connected', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '2', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '2', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '1', tone: 'warning'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '1', tone: 'info'),
    AgentRuntimeStatusBadge(label: 'Timeline', value: '2', tone: 'info'),
  ],
  modelOptions: [
    AgentRuntimeModelOption(id: 'codex-live-model', displayLabel: 'Codex live model', source: 'codex-auth-json', isDefault: true),
  ],
  selectedSessionLabel: 'Runtime validation',
  sessionsTitle: 'Sessions (2)',
  sessionsSubtitle: 'Sessions needing attention',
  timelineTitle: 'Runtime validation',
  timelineSubtitle: 'Recent activity',
  actionsTitle: 'Attention (2)',
  actionsSubtitle: 'Items waiting for owner action',
  detailTitle: 'Runtime detail',
  detailSubtitle: 'Runtime status',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions yet. Create a session to start working.',
  timelineEmptyTitle: 'Runtime validation',
  timelineEmptyText: 'Select a session to inspect recent activity.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [
    AgentRuntimeSessionItem(
      id: 'session-a',
      title: 'Runtime validation',
      status: 'open',
      subtitle: 'runtime-allow · /Users/robertsale/.codex',
      groupLabel: 'Open',
      tone: 'success',
    ),
    AgentRuntimeSessionItem(
      id: 'session-b',
      title: 'Blocked command review',
      status: 'open',
      subtitle: '1 approval pending',
      groupLabel: 'Attention',
      tone: 'warning',
    ),
  ],
  timeline: [
    AgentRuntimeTimelineItem(
      id: 'event-39',
      title: 'User',
      subtitle: 'Please check runtime health.',
      status: 'sent',
      tone: 'user',
    ),
    AgentRuntimeTimelineItem(
      id: 'event-40',
      title: 'Assistant',
      subtitle: 'Health check is passing.',
      status: 'completed',
      tone: 'success',
    ),
    AgentRuntimeTimelineItem(
      id: 'event-41',
      title: 'Tool',
      subtitle: 'Code run completed',
      status: 'completed',
      tone: 'warning',
    ),
    AgentRuntimeTimelineItem(
      id: 'event-42',
      title: 'Approval requested',
      subtitle: 'Search audit requires owner approval',
      status: 'pending',
      tone: 'warning',
    ),
  ],
  selectedConversation: [
    ChatEntry(
      id: 'chat-user-1',
      author: 'User',
      displayLabel: 'User',
      timestamp: null,
      body: 'Please check runtime health.',
      status: 'sent',
    ),
    ChatEntry(
      id: 'chat-tool-1',
      author: 'Tool',
      displayLabel: 'Tool',
      timestamp: null,
      body: 'Execute code',
      subtitle: 'completed',
      kind: 'execute_code',
      status: 'completed',
      command: 'output({"health":"ok"})',
      output: '{"health":"ok"}',
      isTool: true,
    ),
    ChatEntry(
      id: 'image-artifact-1',
      author: 'Runtime',
      displayLabel: 'Image',
      timestamp: null,
      body: 'Captured evidence',
      subtitle: 'image/png · 1 × 1 · 68 bytes',
      kind: 'imageView',
      status: 'stored',
      output: 'agent-runtime-image://session-a/image-artifact-1',
      imagePreviewBase64:
          'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAEklEQVR4nGO4Y2T0HxkzkC4AAMMYI/FM3SW3AAAAAElFTkSuQmCC',
      imagePreviewContentType: 'image/png',
    ),
    ChatEntry(
      id: 'chat-assistant-1',
      author: 'Assistant',
      displayLabel: 'Assistant',
      timestamp: null,
      body: 'Health check is passing.',
      status: 'completed',
    ),
  ],
  actions: [
    AgentRuntimeActionItem(
      id: 'approval-1',
      title: 'Approve command execution',
      subtitle: 'Decision needed',
      kind: 'approval',
      stateText: 'Needs decision',
      tone: 'warning',
    ),
    AgentRuntimeActionItem(
      id: 'registry-request-1',
      title: 'Search audit',
      subtitle: 'Project approval needed',
      kind: 'commandRegistryRequest',
      stateText: 'Needs registry decision',
      tone: 'warning',
    ),
  ],
  roleAdmin: mockAgentRuntimeRoleAdminSelected,
  workflowMemory: mockAgentRuntimeWorkflowMemorySelected,
  controllerFacts: [
    AgentRuntimeFact(label: 'Selected session', value: 'session-a'),
    AgentRuntimeFact(label: 'Connection', value: 'Connected'),
  ],
  operationSurfaces: [
    AgentRuntimeOperationSurface(
      surfaceId: 'session',
      title: 'Session',
      subtitle: 'Runtime validation',
      rows: [
        AgentRuntimeFact(label: 'Session', value: 'Runtime validation'),
        AgentRuntimeFact(label: 'Role', value: 'Runtime Allow'),
        AgentRuntimeFact(label: 'Project', value: 'Runtime'),
        AgentRuntimeFact(label: 'Workdir', value: 'Project workspace'),
        AgentRuntimeFact(label: 'Status', value: 'Open'),
        AgentRuntimeFact(label: 'Created', value: '2026-06-17 08:16'),
        AgentRuntimeFact(label: 'Current turn', value: 'Idle'),
      ],
      actions: [
        AgentRuntimeActionItem(id: 'session-a', title: 'Close session', subtitle: 'Runtime validation', kind: 'closeSession', stateText: 'Ready', tone: 'info'),
        AgentRuntimeActionItem(id: 'session-a', title: 'Archive session', subtitle: 'Runtime validation', kind: 'archiveSession', stateText: 'Ready', tone: 'info'),
        AgentRuntimeActionItem(id: 'session-a', title: 'Fork session', subtitle: 'Runtime validation', kind: 'forkSession', stateText: 'Ready', tone: 'info'),
        AgentRuntimeActionItem(id: 'session-a', title: 'Enable God Mode', subtitle: 'Allow break-glass host zsh shell for this session.', kind: 'godModeGrant', stateText: 'Disabled', tone: 'warning'),
      ],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'compaction',
      title: 'Compaction',
      subtitle: 'Checkpoint and context budget',
      rows: [
        AgentRuntimeFact(label: 'Latest checkpoint', value: 'Completed through turn 12'),
        AgentRuntimeFact(label: 'Boundary', value: 'Latest completed turn'),
        AgentRuntimeFact(label: 'Context estimate', value: '42 KB model-visible'),
        AgentRuntimeFact(label: 'Failed checkpoint', value: 'None'),
      ],
      actions: [
        AgentRuntimeActionItem(
          id: 'session-a',
          title: 'Compact selected session',
          subtitle: 'Create a checkpoint through the latest completed turn.',
          kind: 'compactionManual',
          stateText: 'Uses runtime compaction budget',
          tone: 'warning',
        ),
      ],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'processManager',
      title: 'Process Manager',
      subtitle: 'Managed process handles',
      rows: [
        AgentRuntimeFact(label: 'dev-server', value: 'running · async · terminate at session end'),
      ],
      actions: [
        AgentRuntimeActionItem(id: 'dev-server', title: 'Terminate', subtitle: 'Stop this managed process', kind: 'processTerminate', stateText: 'ready', tone: 'info'),
        AgentRuntimeActionItem(id: 'dev-server', title: 'Send input', subtitle: 'Send text to this process', kind: 'processInput', stateText: 'ready', tone: 'info'),
        AgentRuntimeActionItem(id: 'dev-server', title: 'Flush output', subtitle: 'Read new process output', kind: 'processFlush', stateText: 'ready', tone: 'info'),
      ],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'roleAdmin',
      title: 'Role Admin',
      subtitle: 'Runtime role inventory',
      rows: [
        AgentRuntimeFact(label: 'Runtime Allow', value: 'active · current version'),
      ],
      actions: [],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'workflowMemory',
      title: 'Workflow Memory',
      subtitle: 'Session memory signals',
      rows: [
        AgentRuntimeFact(label: 'Recover generated API drift', value: 'project · helpful 0.5'),
      ],
      actions: [],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'approvals',
      title: 'Approvals',
      subtitle: 'Pending owner decisions',
      rows: [
        AgentRuntimeFact(label: 'Command execution', value: 'Needs decision'),
      ],
      actions: [
        AgentRuntimeActionItem(id: 'approval-1', title: 'Approve', subtitle: 'Command execution', kind: 'approval', stateText: 'Ready', tone: 'warning'),
        AgentRuntimeActionItem(id: 'approval-1', title: 'Resume', subtitle: 'Command execution', kind: 'approvalResume', stateText: 'Ready', tone: 'info'),
      ],
    ),
    AgentRuntimeOperationSurface(
      surfaceId: 'commandRegistry',
      title: 'Command Registry',
      subtitle: 'Pending command requests',
      rows: [
        AgentRuntimeFact(label: 'Search audit', value: 'Needs registry decision'),
      ],
      actions: [
        AgentRuntimeActionItem(id: 'registry-request-1', title: 'Approve command', subtitle: 'Search audit', kind: 'commandRegistryRequest', stateText: 'Ready', tone: 'warning'),
        AgentRuntimeActionItem(id: 'registry-request-1', title: 'Apply policy', subtitle: 'Search audit', kind: 'commandRegistryRequest', stateText: 'Ready', tone: 'info'),
      ],
    ),
  ],
  selectedSessionControlPlane: AgentRuntimeSelectedSessionControlPlane(
    sessionId: 'session-a',
    title: 'Runtime validation',
    name: 'runtime-validation',
    status: 'open',
    roleId: 'runtime-allow',
    projectKey: 'project-a',
    activeModel: 'codex-live-model',
    workdir: '/Users/robertsale/.codex',
    worktreeRoot: '/Users/robertsale/.codex',
    tracked: true,
    modelOptions: [
      AgentRuntimeModelOption(id: 'codex-live-model', displayLabel: 'Codex live model', source: 'runtime', isDefault: true),
      AgentRuntimeModelOption(id: 'gpt-5.4-mini', displayLabel: 'GPT-5.4 Mini', source: 'runtime', isDefault: false),
    ],
    projectOptions: [
      ConversationProject(id: 'project-a', title: 'Runtime', subtitle: 'Runtime project', defaultWorkdir: '/Users/robertsale/.codex', defaultWorktreeRoot: '/Users/robertsale/.codex', defaultRoleId: 'runtime-allow', defaultModel: 'codex-live-model'),
    ],
    godMode: AgentRuntimeGodModeState(active: false, reason: '', grantedBy: '', grantedAt: ''),
    managedProcesses: [
      AgentRuntimeManagedProcessRow(
        id: 'process-dev-server',
        handle: 'dev-server',
        command: 'flutter run --device-id iPad Air 11-inch',
        status: 'running',
        startedAt: '09:14',
        endedAt: '',
        cwd: '/Users/robertsale/.codex/frontend/robdex_app',
        pid: '41231',
        stdinPolicy: 'line',
        endOfTurnBehavior: 'continue',
        endOfSessionBehavior: 'terminate',
        latestOutputSummary: 'Serving design lab on local device.',
        canTerminate: true,
        canFlush: true,
        canInput: true,
      ),
      AgentRuntimeManagedProcessRow(
        id: 'process-checks',
        handle: 'checks',
        command: 'cargo test -p robdex-agent-runtime',
        status: 'completed',
        startedAt: '09:02',
        endedAt: '09:08',
        cwd: '/Users/robertsale/.codex/backend/experiments/agent-runtime',
        pid: '',
        stdinPolicy: 'none',
        endOfTurnBehavior: 'flush',
        endOfSessionBehavior: 'none',
        latestOutputSummary: '208 tests filtered; selected checks passed.',
        canTerminate: false,
        canFlush: true,
        canInput: false,
      ),
    ],
    approvals: [
      AgentRuntimeApprovalCard(
        id: 'approval-1',
        title: 'Approve command execution',
        status: 'pending',
        requiredApprover: 'Owner',
        requestedAt: '4m ago',
        contextSummary: 'Search audit command needs owner approval in the selected session.',
        canDecide: true,
        canResume: false,
        decisionSummary: '',
      ),
      AgentRuntimeApprovalCard(
        id: 'approval-2',
        title: 'Resume paused action',
        status: 'approved',
        requiredApprover: 'Owner',
        requestedAt: '18m ago',
        contextSummary: 'Approved action is waiting for resume.',
        canDecide: false,
        canResume: true,
        decisionSummary: 'Approved for runtime validation.',
      ),
    ],
    commandRequests: [
      AgentRuntimeCommandRequestCard(
        id: 'registry-request-1',
        actionId: 'cmd.registry.audit',
        title: 'Search audit',
        operation: 'Approve command',
        status: 'pending',
        scopeSummary: 'Selected session · project-a',
        policySummary: 'Owner approval required before apply.',
        previewStatus: 'Preview ready',
        applyStatus: 'Not applied',
        canPreview: true,
        canDecide: true,
        canApply: true,
        commandSummary: 'rg --files frontend/robdex_app',
      ),
    ],
    requirementsReview: AgentRuntimeRequirementsReviewPanel(
      active: true,
      status: 'in progress',
      progressSummary: '0 passed · 3 pending',
      reviewerStatus: 'Reviewer ready',
      ownerActionStatus: '',
      latestPacketStatus: 'Waiting for reviewable claims',
    ),
    runningServers: [
      AgentRuntimeFact(label: 'Design Lab', value: '127.0.0.1:8080'),
    ],
    quickActions: [
      AgentRuntimeActionAvailability(id: 'compact', label: 'Compact...', available: true, reason: ''),
      AgentRuntimeActionAvailability(id: 'godMode', label: 'Grant God Mode...', available: true, reason: ''),
      AgentRuntimeActionAvailability(id: 'requirements', label: 'Set Requirements...', available: true, reason: ''),
      AgentRuntimeActionAvailability(id: 'export', label: 'Export Bundle...', available: false, reason: 'No typed export operation is available.'),
      AgentRuntimeActionAvailability(id: 'danger', label: 'Danger Zone', available: true, reason: ''),
    ],
  ),
  outputLog: ['Runtime update received', 'Connection streaming'],
  pendingRequestCount: 0,
);

const mockAgentRuntimeError = AgentRuntimeWorkbenchData(
  connectionState: 'failed',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'unhealthy',
    tone: 'danger',
    title: 'Local runtime is unhealthy',
    message: 'The service process exists but /health is failing.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: false,
    baseUrl: 'http://127.0.0.1:8765',
    diagnostics: ['unhealthy: server process is alive but health check failed'],
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteMalformed,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteMalformed,
  connectionTone: 'danger',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime needs attention',
  watermarkLabel: '—',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'Needs attention', tone: 'danger'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'No session selected',
  sessionsTitle: 'Sessions',
  sessionsSubtitle: 'Sessions needing attention',
  timelineTitle: 'Selected session · No session selected',
  timelineSubtitle: 'Recent activity',
  actionsTitle: 'Attention (0)',
  actionsSubtitle: 'Items waiting for owner action',
  detailTitle: 'Runtime detail',
  detailSubtitle: 'Runtime status',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'Reconnect to load runtime sessions.',
  timelineEmptyTitle: 'No session selected',
  timelineEmptyText: 'Connect to view session activity.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'Connect to load action items.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminInvalid,
  workflowMemory: mockAgentRuntimeWorkflowMemorySelected,
  controllerFacts: [
    AgentRuntimeFact(label: 'Issue', value: 'Service unavailable'),
  ],
  outputLog: ['Connection failed'],
  pendingRequestCount: 0,
  errorMessage: 'Runtime did not respond. Check the service, then refresh discovery.',
);

const mockAgentRuntimeEmpty = AgentRuntimeWorkbenchData(
  connectionState: 'streaming',
  discovery: AgentRuntimeDiscoveryInfo(
    state: 'runningHealthy',
    tone: 'success',
    title: 'Local runtime ready',
    message: 'A healthy local Agent Runtime service was discovered.',
    discoveryPath: '~/Library/Application Support/Robdex Agent Runtime/service/discovery.json',
    connectable: true,
    baseUrl: 'http://127.0.0.1:8765',
  ),
  remoteDiscovery: mockAgentRuntimeIcloudRemoteStale,
  importedRemoteDiscovery: mockAgentRuntimeImportedRemoteStale,
  connectionTone: 'success',
  baseUrl: 'http://127.0.0.1:8765',
  statusLabel: 'Runtime connected · no sessions',
  watermarkLabel: 'current',
  statusBadges: [
    AgentRuntimeStatusBadge(label: 'Connection', value: 'Connected', tone: 'success'),
    AgentRuntimeStatusBadge(label: 'Sessions', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Attention', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Registry requests', value: '0', tone: 'muted'),
    AgentRuntimeStatusBadge(label: 'Command inventory', value: '0', tone: 'muted'),
  ],
  selectedSessionLabel: 'No session selected',
  sessionsTitle: 'Sessions (0)',
  sessionsSubtitle: 'Sessions needing attention',
  timelineTitle: 'Selected session · No session selected',
  timelineSubtitle: 'Recent activity',
  actionsTitle: 'Attention (0)',
  actionsSubtitle: 'Items waiting for owner action',
  detailTitle: 'Runtime detail',
  detailSubtitle: 'Runtime status',
  sessionsEmptyTitle: 'No sessions',
  sessionsEmptyText: 'No sessions yet. Create a session to start working.',
  timelineEmptyTitle: 'No session selected',
  timelineEmptyText: 'Create or select a session to see activity.',
  actionsEmptyTitle: 'No action required',
  actionsEmptyText: 'No approvals, resumable actions, or registry requests need attention.',
  sessions: [],
  timeline: [],
  actions: [],
  roleAdmin: mockAgentRuntimeRoleAdminEmpty,
  workflowMemory: mockAgentRuntimeWorkflowMemoryEmpty,
  controllerFacts: [
    AgentRuntimeFact(label: 'Connection', value: 'Connected'),
    AgentRuntimeFact(label: 'Attention', value: 'None'),
  ],
  outputLog: ['Runtime update received'],
  pendingRequestCount: 0,
);
