[package]
name = "robdex-client-core"
edition.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
reqwest.workspace = true
robdex-protocol = { path = "../robdex-protocol" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
