/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const rinf_send_dart_signal_archive_thread_group_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_archive_thread_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_create_project_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_create_thread_group_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_create_thread_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_decide_approval_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_delete_project_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_delete_thread_group_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_fetch_thread_history_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_initialize_workbench_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_interrupt_thread_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_move_selected_thread_to_group_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_reload_workbench_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_rename_thread_group_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_rename_thread_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_select_project_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_select_thread_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_send_thread_message_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_set_project_orchestrator_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_set_thread_running_state_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_spawn_agent_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_terminate_command_execution_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_thread_compact_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_update_project_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_update_thread_settings_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_update_worker_metadata_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_send_dart_signal_warm_handoff_signal: (a: number, b: number, c: number, d: number) => void;
export const rinf_start_rust_logic_extern: () => void;
export const task_worker_entry_point: (a: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h0a67fa76e899c8a4: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h20bf947e7f788635: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6058dcc82724e2e4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6058dcc82724e2e4_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6058dcc82724e2e4_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb73350ad9f3925dd: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
