import 'workbench_models.dart';
import 'workbench_view_data.dart';

const mockWorkbenchData = WorkbenchViewData(
  projects: [
    ProjectItem(
      id: 'project-codex-home',
      name: 'Codex Control Plane',
      rootPath: '/Users/robertsale/.codex',
      defaultCwd: '/Users/robertsale/.codex',
      autoRouteReplies: false,
      routeApprovalRequests: true,
      preferredModelProvider: null,
      orchestratorDefaultModel: 'gpt-5',
      orchestratorDefaultReasoningEffort: 'high',
      workerDefaultModel: 'gpt-5.4-mini',
      workerDefaultReasoningEffort: 'high',
      qaDefaultModel: 'gpt-5.4-mini',
      qaDefaultReasoningEffort: 'medium',
      designerDefaultModel: 'gpt-5.4-mini',
      designerDefaultReasoningEffort: 'high',
      orchestratorDeveloperInstructions: 'Enforce bridge correctness and role policy.',
      workerDeveloperInstructions: 'Implement the requested slice directly.',
      qaDeveloperInstructions: 'Validate behavior and surface regressions.',
      designerDeveloperInstructions: 'Remove AI slop and push interface quality up.',
      operatorDeveloperInstructions: 'Coordinate local tooling and configuration.',
      hiddenDeveloperInstructions: 'Operate quietly and only when explicitly routed.',
      isSelected: true,
    ),
    ProjectItem(
      id: 'project-ezra',
      name: 'Ezra',
      rootPath: '/Users/robertsale/Code/ezra/ezra/.worktrees',
      defaultCwd: '/Users/robertsale/Code/ezra/ezra/.worktrees',
      autoRouteReplies: true,
      routeApprovalRequests: true,
      preferredModelProvider: null,
      orchestratorDefaultModel: 'gpt-5',
      orchestratorDefaultReasoningEffort: 'high',
      workerDefaultModel: 'gpt-5.4-mini',
      workerDefaultReasoningEffort: 'high',
      qaDefaultModel: 'gpt-5.4-mini',
      qaDefaultReasoningEffort: 'medium',
      designerDefaultModel: 'gpt-5.4-mini',
      designerDefaultReasoningEffort: 'high',
      orchestratorDeveloperInstructions: 'Keep Ezra review lanes disciplined.',
      workerDeveloperInstructions: 'Execute bounded implementation tasks.',
      qaDeveloperInstructions: 'Prove the slice with sanctioned validation.',
      designerDeveloperInstructions: 'Keep Ezra interfaces deliberate and specific.',
      operatorDeveloperInstructions: 'Handle coordination and environment issues.',
      hiddenDeveloperInstructions: 'Remain available for narrow support work.',
      isSelected: false,
    ),
  ],
  selection: WorkspaceSelection(
    projectId: 'project-codex-home',
    projectRootPath: '/Users/robertsale/.codex',
    projectOrchestratorThreadId: 'config-operator',
    projectOrchestratorName: 'Config Operator',
    threadId: 'config-operator',
    threadRole: 'operator',
    projectName: 'Codex Control Plane',
    threadName: 'Config Operator',
    connectionLabel: 'Bridge Connected',
    sandboxMode: 'danger-full-access',
    networkAccess: true,
    approvalPolicy: 'never',
    model: 'gpt-5',
    reasoningEffort: 'high',
    isRunning: true,
  ),
  availableModels: [
    ModelItem(id: 'gpt-5', name: 'GPT-5', hidden: false),
    ModelItem(id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', hidden: false),
  ],
  threads: [
    ThreadItem(
      id: 'config-operator',
      title: 'Config Operator',
      role: 'orchestrator',
      projectName: 'Codex Control Plane',
      preview: 'Bridge stable. Flutter shell scaffold next.',
      isRunning: true,
      unreadCount: 0,
    ),
    ThreadItem(
      id: 'approval-smoke',
      title: 'Approval Smoke Worker',
      role: 'worker',
      projectName: 'Codex Control Plane',
      preview: 'Approval and archive flow recovered.',
      isRunning: false,
      unreadCount: 0,
    ),
    ThreadItem(
      id: 'ezra-wave-b',
      title: 'Ezra Wave B',
      role: 'operator',
      projectName: 'Ezra',
      preview: 'Harness clarity issue tracked.',
      isRunning: false,
      unreadCount: 2,
    ),
  ],
  threadGroups: [
    ThreadGroupItem(
      id: 'group-core',
      title: 'Core Runtime',
      threadIds: ['config-operator'],
      isCollapsed: false,
    ),
  ],
  chatEntries: [
    ChatEntry(
      id: '1',
      author: 'Operator',
      displayLabel: 'Operator',
      timestamp: null,
      body: 'Build the new Robdex frontend here with shared Rust crates.',
    ),
    ChatEntry(
      id: '2',
      author: 'Config Operator',
      displayLabel: 'Config Operator',
      timestamp: null,
      body: 'Resuming interrupted QA-driven reliability sweep from existing agents without re-auditing from scratch.\n[in_progress] Resume the three blocked workers with exact scope and proof constraints.\n[pending] Keep the three QA agents held on warm simulator state pending their paired fixes.\n[pending] Monitor for worker replies and approval requests and steer immediately per constraints.',
      planItems: [
        PlanChecklistItem(
          text: 'Resume the three blocked workers with exact scope and proof constraints.',
          completed: false,
          status: 'in_progress',
        ),
        PlanChecklistItem(
          text: 'Keep the three QA agents held on warm simulator state pending their paired fixes.',
          completed: false,
          status: 'pending',
        ),
        PlanChecklistItem(
          text: 'Monitor for worker replies and approval requests and steer immediately per constraints.',
          completed: false,
          status: 'pending',
        ),
      ],
      isStreaming: true,
    ),
    ChatEntry(
      id: '3',
      author: 'Tooling',
      displayLabel: 'Tooling',
      timestamp: null,
      body: 'Bridge health: connected | runtime: codex-robdex-bridge | mode: mock shell',
      isTool: true,
    ),
  ],
  contextWindowRemainingPercent: 83,
  workspaceFiles: [
    WorkspaceFile(
      path: 'frontend/robdex_app/lib/src/app/robdex_app.dart',
      kind: 'dart',
      status: 'new',
    ),
    WorkspaceFile(
      path: 'backend/crates/robdex-protocol/src/lib.rs',
      kind: 'rust',
      status: 'new',
    ),
    WorkspaceFile(
      path: 'frontend/robdex_app/rinf/schema.rinf',
      kind: 'rinf',
      status: 'new',
    ),
  ],
  inspectorFacts: [
    InspectorFact(label: 'Model', value: 'GPT-5'),
    InspectorFact(label: 'Sandbox', value: 'danger-full-access'),
    InspectorFact(label: 'Network', value: 'enabled'),
    InspectorFact(label: 'Selected Thread', value: 'Config Operator'),
  ],
  liveProcesses: [],
  pendingApprovals: [],
  workerMetadata: null,
  statusHeadline: 'Rust-first Robdex shell',
  statusDetail: 'UI regions are now modular. Next step is swapping mock data for live bridge state from shared Rust core.',
  composerHint: 'Composer is intentionally passive for now. The next slice wires commands and session flow through Rust.',
);
