[package]
name = "hub"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1"
js-sys = "0.3.77"
rinf = "8.10.0"
robdex-client-core = { path = "../../../../backend/crates/robdex-client-core" }
robdex-protocol = { path = "../../../../backend/crates/robdex-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
tokio_with_wasm = { version = "0.8.5", features = ["rt", "sync", "time", "macros"] }
wasm-bindgen = "0.2.100"
